
### peticion de saludo
GET http://localhost:3000/saludo/juan


### lista de productos
GET http://localhost:3000/productos


### producto por id
GET http://localhost:3000/productos/4



### agregar producto
POST http://localhost:3000/productos
Content-Type: application/json 

{
    "title": "producto 1",
    "description": 100,
    "price": 1000
}